import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshState,makeOrder,advanceOrder,routeBetween,routeLength,safeLoad} from '../src/rules.js';
test('A first shift can reach $100 through complete pickup/load/delivery cycles',()=>{let earnings=0;for(let i=0;i<4;i++){let order=makeOrder(i);for(const action of ['collect','load','unload','ring','customer','deliver']){order=advanceOrder(order,action);assert.ok(order);}assert.equal(order.status,'complete');earnings+=order.pay+order.tip;}assert.ok(earnings>=100);});
test('Orders cannot skip loading, waiting for the customer, or handoff',()=>{const order=makeOrder(0);for(const action of ['load','unload','ring','customer','deliver'])assert.equal(advanceOrder(order,action),null);const loaded=advanceOrder(advanceOrder(order,'collect'),'load');assert.equal(advanceOrder(loaded,'deliver'),null);assert.equal(order.status,'pickup');});
test('All generated addresses are residential, excluding the player home',()=>{for(let day=1;day<=30;day++)for(let i=0;i<40;i++){const o=makeOrder(i,day);assert.ok(o.house>=0&&o.house<25);assert.ok(![5,6,7,8,12].includes(o.house));assert.ok(o.shop>=0&&o.shop<4);assert.ok(o.pay>0&&o.tip>=0);}});
test('Navigation starts and ends at exact destinations with axis aligned segments',()=>{const a={x:0,z:14},b={x:-144,z:-64};const route=routeBetween(a,b);assert.deepEqual(route[0],a);assert.deepEqual(route.at(-1),b);for(let i=1;i<route.length;i++)assert.ok(route[i].x===route[i-1].x||route[i].z===route[i-1].z);assert.ok(routeLength(route)>=Math.hypot(b.x-a.x,b.z-a.z));});
test('Save loader preserves all active delivery stages and driving recovery flag',()=>{for(const status of ['pickup','carrying','loaded','atDoor','waiting','ready']){const s=freshState();s.dressed=true;s.order={...makeOrder(0),status};s.inCar=true;const result=safeLoad(JSON.stringify(s));assert.equal(result.order.status,status);assert.equal(result.inCar,true);assert.equal(result.player.y,3.6);}});
test('Broken or incompatible saves fail safely',()=>{for(const raw of [null,'{','null','{}',JSON.stringify({...freshState(),version:99}),JSON.stringify({...freshState(),money:-1}),JSON.stringify({...freshState(),car:{}}),JSON.stringify({...freshState(),order:{...makeOrder(0),house:12}})])assert.equal(safeLoad(raw),null);});
