import * as T from 'three';
import {createWorld} from './world.js';
import {freshState,makeOrder,advanceOrder,routeBetween,routeLength,safeLoad,ROADS} from './rules.js';
const $=id=>document.getElementById(id),canvas=$('game');
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('loading').innerHTML='<b>Не удалось включить 3D</b><span>Нужен браузер с WebGL 2 и аппаратным ускорением.</span>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new T.Scene();scene.background=new T.Color('#142440');scene.fog=new T.FogExp2('#253b57',.0045);
const camera=new T.PerspectiveCamera(68,innerWidth/innerHeight,.08,420);camera.rotation.order='YXZ';scene.add(camera);
const world=createWorld(scene),keys=new Set();let state=freshState(),saved=null;
try{saved=safeLoad(localStorage.getItem('snowpost-save-v1'));}catch{}
let playing=false,paused=true,mapOpen=false,yaw=0,pitch=0,velocity=0,current=null,destination=null,toastUntil=0,frameTime=0,saveTimer=0,uiTimer=0,bellRemaining=0,customer=null,customerTravel=0,lastHungerNotice=false,audioCtx=null,engine=null,engineGain=null;
let touch=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>1,touchX=0,touchY=0,lookId=null,lookPos=null,joyId=null;
if(touch)document.body.classList.add('touch');
// A camera-attached cockpit keeps the entire driving view first person.
const cockpit=new T.Group();camera.add(cockpit);cockpit.visible=false;
function cabinBox(x,y,z,w,h,d,color){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);cockpit.add(m);return m;}
cabinBox(0,-.63,-.72,1.9,.36,.7,'#263943');cabinBox(0,-.45,-1.08,1.87,.05,.3,'#66727a');cabinBox(-.94,.15,-.74,.08,1.65,.09,'#534546');cabinBox(.94,.15,-.74,.08,1.65,.09,'#534546');cabinBox(0,.91,-.52,1.98,.12,1.25,'#565657');
const wheel=new T.Mesh(new T.TorusGeometry(.2,.024,8,24),new T.MeshStandardMaterial({color:'#17282f'}));wheel.position.set(-.34,-.4,-.61);wheel.rotation.x=-.3;cockpit.add(wheel);const dash=cabinBox(.33,-.38,-.87,.4,.24,.035,'#132938');
const dashCanvas=document.createElement('canvas');dashCanvas.width=256;dashCanvas.height=128;const dashTex=new T.CanvasTexture(dashCanvas);const screen=new T.Mesh(new T.PlaneGeometry(.36,.18),new T.MeshBasicMaterial({map:dashTex}));screen.position.set(.33,-.38,-.846);cockpit.add(screen);
const parcel=new T.Group();camera.add(parcel);for(const [x,y,z,w,h,d,c]of [[.34,-.55,-.8,.55,.45,.45,'#bb9366'],[.34,-.317,-.8,.1,.018,.45,'#e4d0a0'],[.34,-.55,-.566,.24,.14,.01,'#f0dfb8']]){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color:c}));m.position.set(x,y,z);parcel.add(m)}parcel.visible=false;
const cargoBox=new T.Mesh(new T.BoxGeometry(.6,.45,.5),new T.MeshStandardMaterial({color:'#c8a171'}));cargoBox.position.set(0,1,1.4);world.playerCar.add(cargoBox);cargoBox.visible=false;
function initSound(){if(!audioCtx&&$('sound').checked){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();engine=audioCtx.createOscillator();engine.type='triangle';engineGain=audioCtx.createGain();engineGain.gain.value=0;engine.connect(engineGain).connect(audioCtx.destination);engine.start();}catch{}}audioCtx?.resume();}
function tone(freq=600,duration=.12,volume=.035){if(!audioCtx||!$('sound').checked)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;toastUntil=frameTime+5;tone(700,.1,.018)}
function save(){state.player.yaw=yaw;state.car={x:world.playerCar.position.x,z:world.playerCar.position.z,angle:world.playerCar.rotation.y};try{localStorage.setItem('snowpost-save-v1',JSON.stringify(state));}catch{$('saveNote').textContent='Браузер не разрешил сохранение. Не закрывайте вкладку.'}}
function closePointer(){if(document.pointerLockElement)document.exitPointerLock();}
function lock(){if(!touch)canvas.requestPointerLock?.()?.catch?.(()=>toast('Для обзора зажмите левую кнопку мыши и двигайте мышь.'));}
function clearInput(){keys.clear();touchX=touchY=0;joyId=null;lookId=null;$('joystick').querySelector('i').style.transform='';}
function menu(open=true){paused=open;clearInput();$('menu').classList.toggle('hidden',!open);$('hud').classList.toggle('hidden',open||!playing);if(open){closePointer();$('start').classList.toggle('hidden',playing);$('resume').classList.toggle('hidden',!playing);$('reset').classList.toggle('hidden',!playing&&!saved)}else lock();}
function applyState(s){state=s;world.playerCar.position.set(s.car.x,0,s.car.z);world.playerCar.rotation.y=s.car.angle;yaw=s.player.yaw||0;pitch=0;velocity=0;const wasDriving=s.inCar;state.inCar=false;world.playerCar.visible=true;cockpit.visible=false;world.playerCar.userData.trunkOpen=false;world.doors.forEach(d=>{d.open=false;d.angle=0});if(s.player.y>2)world.home.door.open=false;if(state.order?.status==='waiting'){state.order.status='atDoor';}if(wasDriving){const p=carPosition(-2.3,0);state.player={x:p.x,z:p.z,y:0,yaw:s.car.angle};yaw=s.car.angle;}if(state.order?.status==='ready')spawnCustomer();setAutoDestination();updateUI();}
function start(){initSound();applyState(saved||freshState());playing=true;menu(false);if(!saved)toast('Доброе утро! Спуститесь по лестнице. Гардероб находится у входа.');}
$('start').onclick=start;$('resume').onclick=()=>{initSound();menu(false)};$('pauseBtn').onclick=()=>menu(true);$('reset').onclick=()=>{if(!confirm('Начать заново? Текущий прогресс будет удалён.'))return;try{localStorage.removeItem('snowpost-save-v1')}catch{}saved=null;if(customer){scene.remove(customer);customer=null}playing=true;applyState(freshState());menu(false);save();};
if(saved){$('start').textContent=`Продолжить · день ${saved.day}`;$('reset').classList.remove('hidden')}
function setAutoDestination(){if(!state.dressed){destination=world.home;return;}const o=state.order;destination=o?(['pickup','carrying'].includes(o.status)?world.shops[o.shop]:world.buildings[o.house]):state.money>=100?world.home:null;}
function changeOrder(action){const n=advanceOrder(state.order,action);if(!n)return false;state.order=n;setAutoDestination();save();updateUI();return true;}
function accept(){if(!state.dressed){toast('Сначала наденьте зимнюю одежду у входа.');return;}if(!state.inCar){toast('Принимать заказы можно в бортовом навигаторе машины.');return;}if(state.order||state.money>=100)return;state.order=makeOrder(state.deliveries,state.day);state.stage='work';setAutoDestination();toast('Заказ принят. Маршрут до заведения отмечен на карте.');save();updateUI();}
$('accept').onclick=accept;
function toggleMap(force){if(!playing||$('dayEnd').classList.contains('hidden')===false)return;mapOpen=typeof force==='boolean'?force:!mapOpen;paused=mapOpen;clearInput();$('mapOverlay').classList.toggle('hidden',!mapOpen);if(mapOpen){closePointer();drawMap($('bigmap'),true);updateUI()}else lock();}
$('mapBtn').onclick=()=>toggleMap();$('touchMap').onclick=()=>toggleMap();$('closeMap').onclick=()=>toggleMap(false);
function carPosition(offsetX,offsetZ){const p=new T.Vector3(offsetX,0,offsetZ).applyAxisAngle(new T.Vector3(0,1,0),world.playerCar.rotation.y);return p.add(world.playerCar.position);}
world.target(0,1,14,'Сесть за руль','enterCar',{dynamic:()=>carPosition(-1.4,-.1),range:3,visible:()=>!state.inCar,priority:1});
world.target(0,1,16,'Багажник','trunk',{dynamic:()=>carPosition(0,2.4),range:2.8,visible:()=>!state.inCar,priority:3,label:()=>{const o=state.order;if(!world.playerCar.userData.trunkOpen)return 'Открыть багажник';if(o?.status==='carrying')return 'Погрузить заказ в машину';if(o?.status==='loaded')return 'Забрать заказ из багажника';if(o?.status==='atDoor')return 'Вернуть заказ в багажник';return 'Закрыть багажник'}});
function blocked(x,z,y,r=.28,driving=false){if(Math.abs(x)>198||Math.abs(z)>198)return true;if(!driving&&!state.inCar&&y<2){const dx=x-world.playerCar.position.x,dz=z-world.playerCar.position.z,a=world.playerCar.rotation.y;const lx=dx*Math.cos(a)-dz*Math.sin(a),lz=dx*Math.sin(a)+dz*Math.cos(a);if(Math.abs(lx)<1.08+r&&Math.abs(lz)<2.15+r)return true;}for(const s of world.solids){if(y+.2>=s.max||y+1.5<=s.min||!s.enabled())continue;if(Math.abs(x-s.x)<s.w/2+r&&Math.abs(z-s.z)<s.d/2+r)return true;}if(driving){for(const b of world.buildings)if(Math.abs(x-b.x)<7.1&&Math.abs(z-b.z)<7.5)return true;for(const v of world.traffic)if(Math.hypot(x-v.g.position.x,z-v.g.position.z)<3.3)return true;}return false;}
function exitCar(){if(!state.inCar)return;if(Math.abs(velocity)>1){toast('Сначала остановите машину.');return;}const tries=[[-2.3,0],[2.3,0],[0,3.3],[0,-3.3]];for(const [x,z]of tries){const p=carPosition(x,z);if(!blocked(p.x,p.z,0)){state.player={x:p.x,z:p.z,y:0,yaw:world.playerCar.rotation.y};yaw=state.player.yaw;pitch=0;state.inCar=false;world.playerCar.visible=true;cockpit.visible=false;save();return;}}toast('Здесь тесно. Припаркуйтесь на свободном месте.');}
function spawnCustomer(){if(customer)scene.remove(customer);const b=world.buildings[state.order.house];b.door.open=true;customer=world.person(b.x,0,b.z+4,'#a18469');customerTravel=0;}
function act(){if(paused||!playing)return;if(state.inCar){toggleMap(true);return;}if(!current)return;const t=current,o=state.order;
 switch(t.action){case 'door':if(o&&t.door===world.buildings[o.house].door&&['atDoor','waiting'].includes(o.status)){toast('Позвоните в звонок справа от двери и дождитесь клиента.');break;}if(t.door===world.home.door&&!state.dressed){toast('На улице −8°. Сначала оденьтесь у гардероба.');break;}t.door.open=!t.door.open;tone(180,.13);break;
 case 'dress':state.dressed=true;state.stage='car';setAutoDestination();toast('Куртка, шапка, шарф и ботинки надеты. Машина перед домом.');save();break;
 case 'eat':state.hunger=100;toast('Вы перекусили. Сытость восстановлена.');save();break;
 case 'sleep':if(Math.hypot(world.playerCar.position.x-world.home.x,world.playerCar.position.z-world.home.z)>32){toast('Сначала верните машину домой.');break;}if(state.money<100){toast('Цель первого рабочего дня — заработать $100.');break;}if(state.order){toast('Сначала завершите текущую доставку.');break;}paused=true;closePointer();$('summary').textContent=`День ${state.day}: заработано $${state.money}. Доставок за всё время: ${state.deliveries}. Машина припаркована, а завтра город снова будет ждать вас.`;$('dayEnd').classList.remove('hidden');save();break;
 case 'enterCar':if(!state.dressed){toast('Перед работой нужно одеться.');break;}if(['carrying','atDoor','waiting','ready'].includes(o?.status)){toast('Сначала положите заказ в багажник.');break;}state.inCar=true;world.playerCar.userData.trunkOpen=false;world.playerCar.visible=false;cockpit.visible=true;yaw=0;pitch=0;velocity=0;toast(o?'WASD — ехать. F — выйти. M — открыть навигатор.':'Откройте карту (M) и примите первый заказ.');save();break;
 case 'trunk':if(!world.playerCar.userData.trunkOpen){world.playerCar.userData.trunkOpen=true;tone(180);break;}if(o?.status==='carrying'){changeOrder('load');world.playerCar.userData.trunkOpen=false;toast('Заказ в багажнике. Теперь отправляйтесь к клиенту.');}else if(o?.status==='loaded'){const b=world.buildings[o.house];if(Math.hypot(world.playerCar.position.x-b.x,world.playerCar.position.z-b.z)>26){toast('Подъедьте к адресу клиента, прежде чем забирать заказ.');break;}changeOrder('unload');toast('Заказ у вас. Позвоните в звонок справа от двери клиента.');}else if(o?.status==='atDoor'){state.order.status='loaded';save();toast('Заказ возвращён в багажник.');}else world.playerCar.userData.trunkOpen=false;break;
 case 'pickup':if(!o){toast('Сначала примите заказ в машине.');break;}if(o.shop!==t.shop){toast('Ваш заказ готовят в другом заведении.');break;}if(changeOrder('collect'))toast(`${o.item}. Отнесите заказ в багажник.`);else toast('Этот заказ уже у вас.');break;
 case 'bell':if(o?.house!==t.building.id){tone(740,.3);toast('Здесь сейчас не ждут доставку.');break;}if(o.status==='atDoor'){changeOrder('ring');bellRemaining=5+Math.random()*5;tone(880,.4);setTimeout(()=>tone(660,.4),250);toast('Дзинь-дон! Клиент подойдёт через 5–10 секунд.');}else if(o.status==='waiting')toast('Клиент уже идёт к двери…');else if(o.status==='ready')toast('Клиент выходит. Подойдите к нему и передайте заказ.');else toast('Достаньте заказ из багажника.');break;
 case 'deliver':deliver();break;
 }updateUI();}
function deliver(){const o=state.order;if(o?.status!=='ready'||customerTravel<1)return;state.money+=o.pay+o.tip;state.total+=o.pay+o.tip;state.deliveries++;state.order=null;state.stage=state.money>=100?'home':'work';toast(`Спасибо! +$${o.pay} за доставку и $${o.tip} чаевых.${state.money>=100?' Цель выполнена — возвращайтесь домой!':''}`);if(customer){scene.remove(customer);customer=null;}world.buildings[o.house].door.open=false;setAutoDestination();save();updateUI();}
$('interact').onclick=act;$('touchAction').onclick=act;$('touchExit').onclick=exitCar;
$('nextDay').onclick=()=>{state.day++;state.money=0;state.dressed=false;state.hunger=100;state.minutes=480;state.stage='dress';state.player={x:-3,z:-4,y:3.6,yaw:Math.PI};state.inCar=false;state.order=null;yaw=Math.PI;pitch=0;world.playerCar.visible=true;cockpit.visible=false;$('dayEnd').classList.add('hidden');paused=false;setAutoDestination();save();lock();toast('Новый день. Сначала оденьтесь у входа.');};
function label(t){return typeof t.label==='function'?t.label():t.label;}
function findTarget(){current=null;if(state.inCar){$('interact').classList.remove('hidden');$('interact').querySelector('span').textContent='Открыть бортовой навигатор';return;}const view=new T.Vector3();camera.getWorldDirection(view);let score=-Infinity;for(const t of world.interactives){if(t.visible&&!t.visible())continue;if(t.action==='dress'&&state.dressed)continue;const p=t.dynamic?t.dynamic():t.pos;if(t.dynamic)p.y=1.1;const diff=p.clone().sub(camera.position),distance=diff.length();if(distance>(t.range||2.65))continue;const dot=diff.normalize().dot(view);if(dot<.48)continue;const s=dot*3-distance*.2+(t.priority||0)*.12;if(s>score){current=t;score=s;}}
 if(customer&&state.order?.status==='ready'){const p=customer.position.clone().add(new T.Vector3(0,1.3,0));if(customerTravel>=1&&p.distanceTo(camera.position)<3.5){current={action:'deliver',label:'Отдать заказ клиенту'}}}
 $('interact').classList.toggle('hidden',!current);if(current)$('interact').querySelector('span').textContent=label(current);$('touchAction').textContent=state.inCar?'Навигатор':current?.action==='deliver'?'Отдать':'Действие';}
function updateUI(){const o=state.order;let title,detail;if(!state.dressed){title='Сначала — потеплее';detail='Спуститесь с 2-го этажа. Гардероб у входной двери: наденьте зимнюю одежду.';}else if(!o&&state.money>=100){title='Дом ждёт';detail='Вы заработали $100. Вернитесь домой, поднимитесь в спальню и ложитесь спать.';}else if(!o){title=state.inCar?'Город ждёт доставку':'Время выезжать';detail=state.inCar?'Откройте карту и примите заказ. Сегодня ваша цель — $100.':'Машина припаркована перед домом. Подойдите к водительской двери и сядьте за руль.';}else{const texts={pickup:['Заберите заказ',`Зайдите в ${world.shops[o.shop].name}. Заказ ждёт у стойки выдачи.`],carrying:['Заказ — в багажник','Подойдите сзади машины, откройте багажник и погрузите коробку.'],loaded:['Доставка в пути',`Адрес: ${world.buildings[o.house].name}. Припаркуйтесь рядом и достаньте заказ.`],atDoor:['Позвоните в дверь',`${world.buildings[o.house].name}. Звонок справа от входа. Заказ у вас в руках.`],waiting:['Клиент уже идёт','Подождите у двери 5–10 секунд. Осталось: '+Math.max(1,Math.ceil(bellRemaining))+' сек.'],ready:['Передайте заказ','Клиент вышел. Подойдите и нажмите «Отдать заказ».']};[title,detail]=texts[o.status];}
 $('objective').textContent=title;$('detail').textContent=detail;$('money').innerHTML=`$${state.money} <em>/ $100</em>`;$('progress').style.width=Math.min(100,state.money)+'%';$('day').textContent=String(state.day).padStart(2,'0');$('time').textContent=`${String(Math.floor(state.minutes/60)%24).padStart(2,'0')}:${String(Math.floor(state.minutes%60)).padStart(2,'0')}`;$('hunger').textContent=`Сытость ${Math.round(state.hunger)}%`;$('cargo').textContent=o?`▣ ${o.item} · $${o.pay} + чаевые`:'';
 $('location').textContent=destination?.name||'Свободный маршрут';const pos=state.inCar?world.playerCar.position:state.player;$('distance').textContent=destination?Math.round(routeLength(routeBetween(pos,destination.front)))+' м':'⌖';$('orderTitle').textContent=o?o.item:state.money>=100?'Смена завершена':'Доставка №'+(state.deliveries+1);$('orderText').textContent=o?`${world.shops[o.shop].name} → ${world.buildings[o.house].name}. Оплата $${o.pay} и возможные чаевые.`:state.money>=100?'Цель выполнена. Выберите дом и возвращайтесь отдыхать.':'Заберите заказ в заведении и доставьте жителю города. Принимать заказы можно за рулём.';$('accept').classList.toggle('hidden',!!o||state.money>=100);$('accept').disabled=!state.inCar||!state.dressed;
 parcel.visible=!!o&&['carrying','atDoor','waiting','ready'].includes(o.status)&&!state.inCar;cargoBox.visible=o?.status==='loaded';$('touchExit').classList.toggle('hidden',!state.inCar);
 const c=dashCanvas.getContext('2d');c.fillStyle='#142d3b';c.fillRect(0,0,256,128);c.fillStyle='#e9c28b';c.font='28px Arial';c.fillText(Math.round(Math.abs(velocity)*3.6)+' км/ч',16,38);c.font='17px Arial';c.fillStyle='#c1d7df';c.fillText('M · КАРТА',16,77);c.fillText(destination?destination.name.slice(0,19):'Принять заказ',16,105);dashTex.needsUpdate=true;
}
for(const b of [world.home,...world.shops]){const btn=document.createElement('button');btn.textContent=(b.home?'⌂ ':'◆ ')+b.name;btn.onclick=()=>{destination=b;drawMap($('bigmap'),true);updateUI();toast('Маршрут: '+b.name)};$('destinations').append(btn)}
function drawMap(el,big=false){const c=el.getContext('2d'),w=el.width,h=el.height,p=state.inCar?world.playerCar.position:state.player,scale=big?Math.min(w,h)/425:1.1,cx=big?0:p.x,cz=big?0:p.z;const xy=(x,z)=>[w/2+(x-cx)*scale,h/2+(z-cz)*scale];c.fillStyle='#193442';c.fillRect(0,0,w,h);c.lineCap='round';for(const r of ROADS){c.strokeStyle='#2d4b5b';c.lineWidth=10*scale;c.beginPath();c.moveTo(...xy(r,-205));c.lineTo(...xy(r,205));c.moveTo(...xy(-205,r));c.lineTo(...xy(205,r));c.stroke();c.strokeStyle='#59717b';c.lineWidth=.6;c.setLineDash([3,7]);c.stroke();c.setLineDash([]);}for(const b of world.buildings){const[x,y]=xy(b.x,b.z);c.fillStyle=b.home?'#ddbf88':b.shop>=0?'#78b5ac':'#687e8d';c.fillRect(x-6*scale,y-6*scale,12*scale,12*scale);if(big){c.font='11px Arial';c.textAlign='center';c.fillStyle=b.home?'#f6dca4':b.shop>=0?'#badbd4':'#aabcc6';c.fillText(b.home?'ДОМ':b.shop>=0?['ПЕКАРНЯ','ПИЦЦЕРИЯ','МАРКЕТ','КОФЕЙНЯ'][b.shop]:b.id+1,x,y+18*scale);}}
 if(destination){const pts=routeBetween(p,destination.front);c.strokeStyle='#f6bf73';c.lineWidth=big?3:2.5;c.beginPath();pts.forEach((v,i)=>{const a=xy(v.x,v.z);i?c.lineTo(...a):c.moveTo(...a)});c.stroke();const[x,y]=xy(destination.x,destination.z);c.strokeStyle='#ffdc9b';c.lineWidth=2;c.beginPath();c.arc(x,y,12*scale,0,Math.PI*2);c.stroke();}
 const[x,y]=xy(p.x,p.z);c.save();c.translate(x,y);c.rotate(state.inCar?world.playerCar.rotation.y:yaw);c.fillStyle='#f4f2e6';c.shadowColor='#eaf4ff';c.shadowBlur=10;c.beginPath();c.moveTo(0,-8);c.lineTo(-5,5);c.lineTo(0,3);c.lineTo(5,5);c.closePath();c.fill();c.restore();if(big){c.font='12px Arial';c.fillStyle='#a7becb';c.textAlign='left';c.fillText('СЕВЕР ↑',22,27);c.fillText('100 м',22,h-20);c.strokeStyle='#a7becb';c.beginPath();c.moveTo(22,h-37);c.lineTo(22+100*scale,h-37);c.stroke();}}
$('bigmap').onclick=e=>{const el=$('bigmap'),rect=el.getBoundingClientRect(),scale=Math.min(el.width,el.height)/425,x=((e.clientX-rect.left)/rect.width*el.width-el.width/2)/scale,z=((e.clientY-rect.top)/rect.height*el.height-el.height/2)/scale;let nearest=null,d=Infinity;for(const b of world.buildings){const dd=Math.hypot(b.x-x,b.z-z);if(dd<d){d=dd;nearest=b}}if(d<26){destination=nearest;drawMap(el,true);updateUI();}};
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('phone').classList.toggle('hidden',!(touch&&Math.min(innerWidth,innerHeight)<540));}window.addEventListener('resize',resize);resize();
$('quality').onchange=()=>{const q=$('quality').value;renderer.setPixelRatio(q==='low'?1:Math.min(devicePixelRatio,q==='high'?2:1.5));world.snowPoints.geometry.setDrawRange(0,q==='low'?500:q==='high'?1800:1100);scene.fog.density=q==='low'?.006:.0045;};$('quality').onchange();$('sound').onchange=()=>{if(!$('sound').checked&&engineGain)engineGain.gain.value=0;else initSound();};
window.addEventListener('keydown',e=>{if(!$('dayEnd').classList.contains('hidden'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){if(mapOpen)toggleMap(false);else if(playing)menu(!paused);return;}if(e.code==='KeyM'&&playing&&$('menu').classList.contains('hidden')){toggleMap();return;}if(paused)return;keys.add(e.code);if(e.code==='KeyE')act();if(e.code==='KeyF')exitCar();});window.addEventListener('keyup',e=>keys.delete(e.code));
let dragging=false;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&playing&&!paused){dragging=true;lock();}});window.addEventListener('pointerup',()=>dragging=false);window.addEventListener('mousemove',e=>{if(paused||!playing||(!document.pointerLockElement&&!dragging))return;yaw-=e.movementX*.0022;pitch=Math.max(-1.2,Math.min(1.2,pitch-e.movementY*.0022));if(state.inCar)yaw=Math.max(-1.35,Math.min(1.35,yaw));});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&playing&&!paused&&!mapOpen)menu(true);});window.addEventListener('blur',()=>{clearInput();if(playing&&!paused&&!mapOpen)menu(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){save();if(!paused&&!mapOpen)menu(true)}});window.addEventListener('beforeunload',()=>{if(playing)save()});
const joystick=$('joystick');joystick.addEventListener('pointerdown',e=>{joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joyMove(e)});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joyMove(e)});function joyMove(e){const r=joystick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/46,dy=(e.clientY-r.top-r.height/2)/46,l=Math.max(1,Math.hypot(dx,dy));touchX=dx/l;touchY=-dy/l;joystick.querySelector('i').style.transform=`translate(${touchX*40}px,${-touchY*40}px)`;}function joyEnd(){joyId=null;touchX=touchY=0;joystick.querySelector('i').style.transform='';}joystick.addEventListener('pointerup',joyEnd);joystick.addEventListener('pointercancel',joyEnd);
const look=$('lookZone');look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lookPos={x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||paused)return;yaw-=(e.clientX-lookPos.x)*.004;pitch=Math.max(-1.2,Math.min(1.2,pitch-(e.clientY-lookPos.y)*.004));if(state.inCar)yaw=Math.max(-1.35,Math.min(1.35,yaw));lookPos={x:e.clientX,y:e.clientY};});for(const event of ['pointerup','pointercancel'])look.addEventListener(event,()=>lookId=null);
function move(dt){const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touchY,side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touchX;
 if(state.inCar){velocity+=forward*8*dt;velocity*=Math.exp(-dt*(Math.abs(forward)>.05?.19:2));velocity=Math.max(-5,Math.min(16,velocity));const car=world.playerCar;car.rotation.y-=side*dt*.95*Math.min(1,Math.abs(velocity)/2)*Math.sign(velocity);const nx=car.position.x-Math.sin(car.rotation.y)*velocity*dt,nz=car.position.z-Math.cos(car.rotation.y)*velocity*dt;if(!blocked(nx,nz,0,1.35,true)){car.position.x=nx;car.position.z=nz;}else{if(Math.abs(velocity)>3){tone(90,.1,.06);toast('Препятствие. Сдайте назад и объедьте.')}velocity=0;}state.player.x=car.position.x;state.player.z=car.position.z;state.player.y=0;camera.position.copy(carPosition(-.38,-.1));camera.position.y=1.48;camera.rotation.set(pitch,car.rotation.y+yaw,0,'YXZ');wheel.rotation.z=side*-.55;$('speed').textContent=Math.round(Math.abs(velocity)*3.6)+' км/ч · F — выйти';}
 else{let f=forward,s=side;const len=Math.max(1,Math.hypot(f,s));f/=len;s/=len;const speed=(keys.has('ShiftLeft')?5:3.3)*(state.hunger<15?.75:1);const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*speed*dt,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*speed*dt,p=state.player;const y=p.y;if(!blocked(p.x+dx,p.z,y))p.x+=dx;if(!blocked(p.x,p.z+dz,y))p.z+=dz;let ground=0;const h=world.home;if(Math.abs(p.x-h.x)<5.8&&Math.abs(p.z-h.z)<5.8){if(p.x>h.x+3.05&&p.x<h.x+5.6)ground=T.MathUtils.clamp((5.25-(p.z-h.z))/10*3.6,0,3.6);else if(p.y>2.5)ground=3.6;}if(ground>p.y+.6&&p.x>h.x+3.05){p.x-=dx;p.z-=dz;ground=p.y;}p.y+=(ground-p.y)*Math.min(1,dt*14);camera.position.set(p.x,p.y+1.65+(Math.abs(f)+Math.abs(s)>.1?Math.sin(frameTime*9)*.025:0),p.z);camera.rotation.set(pitch,yaw,0,'YXZ');$('speed').textContent='';}
}
let previous=performance.now();function tick(now){requestAnimationFrame(tick);const dt=Math.min(.05,(now-previous)/1000);previous=now;frameTime+=dt;if(playing&&!paused){move(dt);state.minutes=Math.min(22*60,state.minutes+dt*1.5);state.hunger=Math.max(0,state.hunger-dt*.018);if(state.hunger<20&&!lastHungerNotice){toast('Вы проголодались. Дома можно открыть холодильник и поесть.');lastHungerNotice=true;}if(state.hunger>30)lastHungerNotice=false;world.update(dt,frameTime,state.inCar?world.playerCar.position:state.player);findTarget();if(state.order?.status==='waiting'){bellRemaining-=dt;if(bellRemaining<=0){changeOrder('customer');spawnCustomer();toast('Здравствуйте! Передайте заказ клиенту.');}}if(customer){const b=world.buildings[state.order.house];customerTravel=Math.min(1,customerTravel+dt*.45);customer.position.z=b.z+4+customerTravel*3.8;}saveTimer+=dt;if(saveTimer>5){save();saveTimer=0;}}
 else if(!playing){camera.position.set(22,11,28);camera.lookAt(0,3,0);world.update(dt,frameTime,{x:0,z:0});}
 const tr=world.playerCar.userData.trunk;tr.rotation.x+=( (world.playerCar.userData.trunkOpen?-1.6:0)-tr.rotation.x)*Math.min(1,dt*8);
 if(engineGain){engineGain.gain.setTargetAtTime(state.inCar&&!paused&&$('sound').checked?.035:0,audioCtx.currentTime,.1);engine.frequency.setTargetAtTime(35+Math.abs(velocity)*4,audioCtx.currentTime,.1);}
 if(frameTime>toastUntil)$('toast').style.opacity=0;uiTimer+=dt;if(uiTimer>.15){uiTimer=0;if(playing){updateUI();drawMap($('minimap'));if(mapOpen)drawMap($('bigmap'),true);}}renderer.render(scene,camera);}
$('loading').classList.add('hidden');$('menu').classList.remove('hidden');requestAnimationFrame(tick);
