export const ROADS=[-180,-108,-36,36,108,180];
export const SHOP_NAMES=['Пекарня «Крошка»','Пиццерия «Огонёк»','Маркет «У дома»','Кофейня «Север»'];
export const freshState=()=>({version:1,day:1,money:0,total:0,deliveries:0,dressed:false,stage:'dress',order:null,hunger:100,minutes:480,car:{x:0,z:14,angle:Math.PI/2},player:{x:-3,z:-4,y:3.6,yaw:Math.PI},inCar:false});
export function makeOrder(index,day=1){const tips=[7,4,9,6,8];return {id:index+1,shop:index%4,house:[0,1,2,3,4,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24][(index*7+day*3)%20],pay:22+(index%3)*3,tip:tips[index%tips.length],item:['Пакет свежей выпечки','Две горячие пиццы','Продукты на ужин','Кофе и десерты'][index%4],status:'pickup'};}
export function advanceOrder(order,action){const stages={pickup:['collect','carrying'],carrying:['load','loaded'],loaded:['unload','atDoor'],atDoor:['ring','waiting'],waiting:['customer','ready'],ready:['deliver','complete']};const next=stages[order?.status];if(!next||next[0]!==action)return null;return {...order,status:next[1]};}
export function nearestRoad(v){return ROADS.reduce((a,b)=>Math.abs(v-b)<Math.abs(v-a)?b:a);}
export function routeBetween(from,to){const az=nearestRoad(from.z),bz=nearestRoad(to.z),rx=nearestRoad(to.x);return [{x:from.x,z:from.z},{x:from.x,z:az},{x:rx,z:az},{x:rx,z:bz},{x:to.x,z:bz},{x:to.x,z:to.z}].filter((p,i,a)=>!i||p.x!==a[i-1].x||p.z!==a[i-1].z);}
export function routeLength(points){return points.slice(1).reduce((d,p,i)=>d+Math.hypot(p.x-points[i].x,p.z-points[i].z),0);}
export function safeLoad(raw){try{const s=JSON.parse(raw);if(s?.version!==1||!Number.isFinite(s.money)||s.money<0||!Number.isFinite(s.day)||s.day<1)return null;const f=freshState();if(!Number.isInteger(s.deliveries)||s.deliveries<0||!Number.isFinite(s.total)||s.total<0)return null;if(!s.player||!s.car||![s.player.x,s.player.z,s.player.y,s.player.yaw,s.car.x,s.car.z,s.car.angle,s.hunger,s.minutes].every(Number.isFinite))return null;if(s.order&&(!Number.isFinite(s.order.pay)||s.order.pay<0||!Number.isFinite(s.order.tip)||s.order.tip<0||typeof s.order.item!=='string'||!Number.isInteger(s.order.house)||s.order.house<0||s.order.house>24||[5,6,7,8,12].includes(s.order.house)||!Number.isInteger(s.order.shop)||s.order.shop<0||s.order.shop>3||!['pickup','carrying','loaded','atDoor','waiting','ready'].includes(s.order.status)))return null;return {...f,...s,inCar:!!s.inCar};}catch{return null;}}
